=== aerys/minko/plugin/devil/lib/devil/DevIL-docs/DevilDoc.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT a EMPTY>
<!ATTLIST a
    from CDATA #IMPLIED
    description CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!ELEMENT link (a)*>
<!ATTLIST link
    verbose CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!ELEMENT description (#PCDATA)>

<!ELEMENT param EMPTY>
<!ATTLIST param
    description CDATA #IMPLIED
    type CDATA #IMPLIED
    name CDATA #IMPLIED
  >

<!ELEMENT return (#PCDATA)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT entity (link|description|param|return|name)*>
<!ATTLIST entity
    type CDATA #IMPLIED
  >

<!ELEMENT set (entity)*>
<!ATTLIST set
    name CDATA #IMPLIED
  >
  
<!ELEMENT doc (set)*>

=== aerys/minko/plugin/devil/lib/devil/DevIL-docs/DevilDoc.xml
<?xml version="1.0"?>
<!DOCTYPE doc SYSTEM "DevilDoc.dtd"><!-- Matrixes are expressed like a matrix, the scale and offset -->

<doc>
  <set name="IL">
    <entity type="function">
      <name>ilActiveImage</name>
      <return>ILboolean</return>
      <param description="Animation numer to select as current." name="Number" type="ILuint" />ma
			<description>ilActiveImage sets the current image to be an image in an animation chain</description>
      <link name="Errors" verbose="true">
        <a from="IL" name="IL_ILLEGAL_OPERATION" />
        <a from="IL" name="IL_INTERNAL_ERROR" />
      </link>
      <link name="See Also" verbose="false">
        <a from="IL" name="ilBindImage" />
        <a from="IL" name="ilActiveMipmap" />
        <a from="IL" name="ilActiveLayer" />
        <a from="IL" name="ilGenImages" />
      </link>
    </entity>
    <entity type="function">
      <name>ilActiveMipmap</name>
      <return>ILboolean</return>
      <param description="Mipmap level to select as current." name="Number" type="ILuint" />
      <description>ilActiveMipmap sets a mipmap of the image as the current mipmap. Currently, the only way to generate mipmaps is by calling iluBuildMipmaps. If neither function has been called for the current image, no mipmaps exist for it. If Number is 0, then the current base image is set.</description>
      <link name="Errors" verbose="true">
        <a from="IL" name="IL_ILLEGAL_OPERATION" />
        <a from="IL" name="IL_INTERNAL_ERROR" />
      </link>
      <link name="See Also" verbose="false">
        <a from="IL" name="ilGenImages" />
        <a from="IL" name="ilBindImage" />
        <a from="IL" name="ilActiveImage" />
        <a from="ILU" name="iluBuildMipmaps" />
        <a from="IL" name="ilActiveLayer" />
      </link>
    </entity>
    <entity type="function">
      <name>ilBindImage</name>
      <return>ILvoid</return>
      <param description="The name of an image." name="Image" type="ILuint" />
      <description>The ilBindImage function creates a named image. Image names are ILuint&apos;s, with zero being reserved as the default image. The default image is generated by ilCreateDefaultTex. The only reason the default image would be NULL is if OpenIL could not create the default image, due to memory constraints of the system, so always heed the IL_OUT_OF_MEMORY error. Any dimension image may be bound with ilBindImage. When ilBindImage is called, the bound image remains bound until ilBindImage is called again with a different value in Image.</description>
      <link name="Errors" verbose="true">
        <a from="IL" name="IL_ILLEGAL_OPERATION" />
      </link>
      <link name="See Also" verbose="false">
        <a from="IL" name="ilGenImages" />
        <a from="IL" name="ilDeleteImages" />
        <a from="IL" name="ilCreateDefaultTex" />
        <a from="IL" name="ilGetError" />
      </link>
    </entity>
    <entity type="function">
      <name>ilClearImage</name>
      <return>ILboolean</return>
      <description>ilClearImage simply clears the image to the colours specified in ilClearColour. If the current image is of format IL_COLOR_INDEX, the image is cleared to all zeros, and the palette is changed to one entry of all zeros. If the current image is of format IL_LUMINANCE, the image is cleared to all zeros.</description>
      <link name="Errors" verbose="true">
        <a from="IL" name="IL_ILLEGAL_OPERATION" />
      </link>
      <link name="See Also" verbose="false">
        <a from="IL" name="ilGenImages" />
        <a from="IL" name="ilBindImage" />
        <a from="IL" name="ilClearColour" />
      </link>
    </entity>
    <entity type="function">
      <name>ilConvertImage</name>
      <return>ILboolean</return>
      <param description="The format the current image should be converted to." name="DestFormat" type="ILenum" />
      <param description="The type the current image should be converted to." name="DestType" type="ILenum" />
      <description>ilConvertImage converts the current bound image from its format/type to DestFormat and DestType. Almost all conversions are allowable.</description>
      <link name="Formats" verbose="true">
        <a name="IL_RGB" description="" />
        <a name="IL_RGBA" description="" />
        <a name="IL_BGR" description="" />
        <a name="IL_BGRA" description="" />
        <a name="IL_LUMINANCE" description="" />
        <a name="IL_LUMINANCE_ALPHA" description="" />
        <a name="IL_COLOUR_INDEX" description="" />
      </link>
      <link name="Types" verbose="true">
        <a name="IL_BYTE" description="" />
        <a name="IL_UNSIGNED_BYTE" description="" />
        <a name="IL_SHORT" description="" />
        <a name="IL_UNSIGNED_SHORT" description="" />
        <a name="IL_INT" description="" />
        <a name="IL_UNSIGNED_INT" description="" />
        <a name="IL_FLOAT" description="" />
        <a name="IL_DOUBLE" description="" />
      </link>
      <link name="Errors" verbose="true">
        <a from="IL" name="IL_ILLEGAL_OPERATION" />
        <a from="IL" name="IL_INVALID_CONVERSION" description="DestFormat and/or DestType was an invalid identifier." />
        <a from="IL" name="IL_OUT_OF_MEMORY" description="Could not allocate memory for the converted image data." />
      </link>
      <link name="See Also" verbose="false">
        <a from="IL" name="ilGenImages" />
        <a from="IL" name="ilBindImage" />
        <a from="IL" name="ilGetBoolean" />
        <a from="IL" name="ilGetBooleanv" />
        <a from="IL" name="ilGetInteger" />
        <a from="IL" name="ilGetIntegerv" />
        <a from="IL" name="ilConvertPal" />
      </link>
    </entity>
    <entity type="function">
      <name>ilCopyImage</name>
      <return>ILboolean</return>
      <param description="Name of an image to copy to the current image." name="Src" type="ILuint" />
      <description>ilCopyImage copies the attributes and data from the image named in Src. The same image bound before calling ilCopyImage remains bound afterward.</description>
      <link name="Errors" verbose="true">
        <a from="IL" name="IL_ILLEGAL_OPERATION" />
        <a from="IL" name="IL_OUT_OF_MEMORY" description="Could not allocate memory for the converted image data." />
      </link>
      <link name="See Also" verbose="false">
        <a from="IL" name="ilGenImages" />
        <a from="IL" name="ilBindImage" />
      </link>
    </entity>
    <entity type="function">
      <name>ilCopyPixels</name>
      <return>ILvoid</return>
      <param description="Where to begin copying pixels from in the x direction." name="XOff" type="ILuint" />
      <param description="Where to begin copying pixels from in the y direction." name="YOff" type="ILuint" />
      <param description="Where to begin copying pixels from in the z direction." name="ZOff" type="ILuint" />
      <param description="How many pixels to copy in the x direction." name="Width" type="ILuint" />
      <param description="How many pixels to copy in the y direction." name="Height" type="ILuint" />
      <param description="How many pixels to copy in the z direction." name="Depth" type="ILuint" />
      <param description="The desired format the output should be." name="Format" type="ILenum" />
      <param description="The desired type the output should be." name="Type" type="ILenum" />
      <param description="User-defined buffer to copy the image data to." name="Data" type="ILvoid *" />
      <description>ilCopyPixels has very simple behaviour. It simply copies a block of pixels from the current image to the Data buffer. XOff, YOff and ZOff can be used to skip a certain number of pixels in each respective direction. If XOff + Width, YOff + Height and/or ZOff + Depth is greater than the current image&apos;s width, height or depth, only the current image&apos;s width, height or depth number of pixels will be copied to Data.</description>
      <link name="Errors" verbose="true">
        <a from="IL" name="IL_ILLEGAL_OPERATION" />
        <a from="IL" description="Format did not match the current image&apos;s format. Use ilGetInteger to obtain the current image&apos;s format." name="IL_INVALID_CONVERSION" />
      </link>
      <link name="See Also" verbose="false">
        <a from="IL" name="ilGenImages" />
        <a from="IL" name="ilBindImage" />
        <a from="IL" name="ilGetInteger" />
      </link>
    </entity>
    <entity type="function">
      <name>ilDefaultImage</name>
      <return>ILboolean</return>
      <description>ilDefaultImage creates an ugly 64x64 image of 8x8 black and yellow squares to form a checkerboard pattern. In future versions of OpenIL, there may be an option that will load this image if an image-loading function failed (unless memory could not be allocated). This way, the user can easily tell if an image was not loaded. Plus, the calling program can continue normally, even though it will have an ugly image. ;-)</description>
      <link name="Errors" verbose="true">
        <a from="IL" name="IL_ILLEGAL_OPERATION" />
        <a from="IL" name="IL_OUT_OF_MEMORY" />
      </link>
      <link name="See Also" verbose="false">
        <a from="IL" name="ilGenImages" />
        <a from="IL" name="ilBindImage" />
      </link>
    </entity>
    <entity type="function">
      <name>ilDeleteImages</name>
      <return>ILvoid</return>
      <param description="Number of image names to delete." name="Num" type="ILsizei" />
      <param description="Pointer to image names to delete." name="Images" type="const ILuint *" />
      <description>ilDeleteImages deletes Num image names specified in Images. After a texture is deleted, its characteristics and dimensions are undefined, and the name may be reused byilGenImages. ilDeleteImages ignores zeros and out-of-bounds image names. If the current image is deleted, the binding reverts to the default image (image name of 0).</description>
      <link name="Errors" verbose="true">
